import type { Metadata } from 'next';
import './globals.css';

import localFont from 'next/font/local';

const spaceMono = localFont({
  src: [
    { path: '../public/assets/fonts/SpaceMono-Regular.ttf', weight: '400' },
    { path: '../public/assets/fonts/SpaceMono-Bold.ttf', weight: '700' },
  ],
  variable: '--font-space-mono',
  display: 'swap',
});

const spaceGrotesk = localFont({
  src: [
    { path: '../public/assets/fonts/SpaceGrotesk-Regular.ttf', weight: '400' },
    { path: '../public/assets/fonts/SpaceGrotesk-Medium.ttf', weight: '500' },
    { path: '../public/assets/fonts/SpaceGrotesk-Bold.ttf', weight: '700' },
  ],
  variable: '--font-space-grotesk',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${spaceMono.variable} ${spaceGrotesk.variable}`}>
      <body>{children}</body>
    </html>
  );
}
