export const testKings = [
  {
    email: 'sune@reload.dk',
    avatar_url: 'https://s.gravatar.com/avatar/9f0575e0c15157173cab66b7dda39bb2?size=800',
    full_name: 'Sune Gamst',
    user_id: 714192,
    votes: [
      'for at have overskud til at tage en praktikant under vingerne',
      'kæmpe tak for at hjælpe med afvikling af workshop',
      'for at have praktikant-meister numero uno',
    ],
    title: 'KarmaKungfu',
    week: 19,
    year: 2025,
  },
  {
    email: 'kb@reload.dk',
    avatar_url: 'https://s.gravatar.com/avatar/848b50174425dea346dcc83232748e21?size=800',
    full_name: 'Kasper Birch',
    user_id: 482463,
    votes: ['evigt hjælpsom'],
    title: 'KarmaKronpris(sesse)',
    week: 18,
    year: 2025,
  },
  {
    email: 'sh@reload.dk',
    avatar_url: 'https://s.gravatar.com/avatar/e471e12e180e4e1d8f7d7b67dc2b5e85?size=800',
    full_name: 'Sofie Hvidt',
    user_id: 894949,
    votes: [
      'for at være for sindssyg til plakat-magi!',
      'for at starte i Reload og medbringe masser af god energi! :)',
      'for at være mega god til at lave kaffe! :coffee:',
    ],
    title: 'KarmaConnoisseur',
    week: 17,
    year: 2025,
  },
  {
    email: 'anne@reload.dk',
    avatar_url: 'https://s.gravatar.com/avatar/72ace2c0a967413ebc6635b24da8cfcd?size=800',
    full_name: 'Anne Skovbo',
    user_id: 302534,
    votes: ['for at være fantastisk med vafler til morgenmad'],
    title: 'KarmaKungfu',
    week: 14,
    year: 2025,
  },
  {
    email: 'jonas@reload.dk',
    avatar_url: 'https://s.gravatar.com/avatar/123abc456def7890abc123def456abc1?size=800',
    full_name: 'Jonas Nielsen',
    user_id: 123321,
    votes: [
      'for at redde deployment i sidste øjeblik :rocket:',
      'super teamwork på klientprojektet!',
    ],
    title: 'KarmaHelt',
    week: 13,
    year: 2025,
  },
  {
    email: 'maria@reload.dk',
    avatar_url: 'https://s.gravatar.com/avatar/0fedcba9876543210fedcba987654321?size=800',
    full_name: 'Maria Jensen',
    user_id: 987654,
    votes: [
      'for at holde overblikket i kaos',
      'for at være den evige projektstyrer med godt humør',
      'for at sikre fredagsmorgenbrød hver uge :bread:',
    ],
    title: 'KarmaKunstner',
    week: 12,
    year: 2025,
  },
];
